[package]
authors = ["bh <bohan-zhang@foxmail.com>"]
edition = "2018"
name = "algorithm"
version = "0.1.0"

license = "MIT"
readme = "README.md"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
insta = "1.21.0"
pretty_assertions = "1.3.0"
